### ISSUE TITLE
UI issue in navbar and in header section

### ISSUE THREAD

**Issue by negia7014** [piug-07/blogzen-OpenSource#7]
in navbar all section be equal size and should be equal space and in header section the search bar not properly allign 
please assign this issue to me 

![image](https://github.com/piug-07/blogzen-OpenSource/assets/111852535/515f396d-92a6-422a-b889-39212824454b)

**Comment by Anou25** [comment]
Hi, I want to work on this issue please assign it to me, I can make it more appealing,  I have experience in designing as well.

**Comment by Sathya-reddy1658** [comment]
I have already worked on this issue
![image](https://github.com/piug-07/blogzen-OpenSource/assets/154568696/9c528051-412d-4727-8ed2-e714db7e79d9)
this is how it look now , i intentionally added little extra space before calendar button in order to differentiate between them.
please assign me this issue and ill make a PR  , or if any changes needed please let me know
